stages:
  - triggers
  - postbuild
  - report

agent_x86_64:
  stage: triggers
  variables:
    LONG_ARCH: x86_64
    SHORT_ARCH: amd64
    LLVM_ARCH: x86_64
  trigger:
    include: .gitlab-ci-x64.yml
    strategy: depend
  rules:
    - when: always


agent_arm64:
  stage: triggers
  variables:
    LONG_ARCH: aarch64
    SHORT_ARCH: arm64
    LLVM_ARCH: arm64
  trigger:
    include: .gitlab-ci-arm.yml
    strategy: depend
  rules:
    - when: always

.merge_docker_manifest: &merge_docker_manifest
  stage: postbuild
  needs: [ agent_x86_64, agent_arm64 ]
  trigger:
    include: .gitlab-ci-docker.yml
    strategy: depend
  rules:
    - when: on_success

merge_linux_docker_manifest:
  <<: *merge_docker_manifest
  variables:
    DST_REPOSITORY: quay.io/stackstate/stackstate-process-agent-test
    DST_TAG: "$CI_COMMIT_REF_NAME"

merge_extra_linux_docker_manifest:
  <<: *merge_docker_manifest
  variables:
    DST_REPOSITORY: quay.io/stackstate/stackstate-process-agent-test
    DST_TAG: "$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"

merge_k8s_docker_manifest:
  <<: *merge_docker_manifest
  variables:
    DST_REPOSITORY: quay.io/stackstate/stackstate-k8s-process-agent
    DST_TAG: "$CI_COMMIT_REF_NAME"

merge_extra_k8s_docker_manifest:
  <<: *merge_docker_manifest
  variables:
    DST_REPOSITORY: quay.io/stackstate/stackstate-k8s-process-agent
    DST_TAG: "$CI_COMMIT_SHORT_SHA"

notify-on-master-fail:
  before_script:
    - apk add --no-cache bash curl
  image: ${DOCKER_PROXY_URL}/library/alpine:latest
  only:
    - stac-21872
    - master
  script:
    - SUITE=build ./.cerberus/cerberus_notify_failure.sh
  stage: report
  tags:
    - sts-k8s-m-runner
  when: on_failure
