stages:
  - triggers

agent_x86_64:
  stage: triggers
  variables:
    ARCH: x64
    DD_ARCH: x64
  trigger:
    include: .gitlab-ci-x64.yml
    strategy: depend
  rules:
    - when: always


agent_arm64:
  stage: triggers
  variables:
    ARCH: arm64
    DD_ARCH: arm64
  trigger:
    include: .gitlab-ci-arm.yml
    strategy: depend
  rules:
    - when: always