variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - alias: docker
    command:
      - --experimental
      - --tls=false
    name: ${DOCKER_PROXY_URL}/docker:20-dind

stages:
  - merge-manifest
  - acceptance

merge-manifest:
  stage: merge-manifest
  image: ${DOCKER_PROXY_URL}/docker:20-git
  script:
    - echo "${quay_password}" | docker login --username=${quay_user} --password-stdin quay.io
    - docker manifest create "${DST_REPOSITORY}:${DST_TAG}" --amend "${DST_REPOSITORY}:${DST_TAG}-amd64" --amend "${DST_REPOSITORY}:${DST_TAG}-arm64"
    - docker manifest push "${DST_REPOSITORY}:${DST_TAG}"

beest_k8s_1_33_containerd_trigger_verification:
  stage: acceptance
  variables:
    PROCESS_AGENT_BRANCH_UNDER_TEST: "$CI_COMMIT_REF_NAME"
    PROCESS_AGENT_HASH_UNDER_TEST: "$CI_COMMIT_SHORT_SHA"
    TRIGGER_X86_TESTS: "true"
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
      when: on_success
    - if: $CI_COMMIT_BRANCH || $CI_MERGE_REQUEST_IID
      when: manual
      allow_failure: true
  needs:
    - merge-manifest
  trigger:
    project: stackvista/integrations/beest