stages:
  - prebuild
  - build
  - test
  - publish

variables:
  SRC_PATH: /src/github.com/StackVista/stackstate-process-agent
  STS_AWS_BUCKET: stackstate-process-agent-2-test
  STS_REPO_BRANCH_NAME: $CI_COMMIT_REF_NAME
  PACKAGING_BRANCH: $CI_COMMIT_REF_NAME
  STS_DOCKER_RELEASE_REPO: stackstate-process-agent
  STS_DOCKER_TEST_REPO: stackstate-process-agent-test
  STS_DOCKER_K8S_REPO: stackstate-k8s-process-agent
  GO111MODULE: "on"
  QUAY_REGISTRY: quay.io
  DOCKER_REGISTRY: docker.io
  RUNNER7_DIR: $CI_PROJECT_DIR/.cd-builders/runner-gitlab-centos7
  VERSION_LOGIC: '(if [ "$${CI_COMMIT_TAG}" == "" ]; then echo "$${CI_COMMIT_SHORT_SHA}"; else echo "$${CI_COMMIT_TAG}"; fi);'
  LINUX_BUILDER: ${DOCKER_PROXY_URL}/datadog_build_deb_x64:3e691150
  GOPATH: "$CI_PROJECT_DIR/.go"

.go_process_agent_cache:
  cache:
    - key:
        files:
          - go.mod
          - go.sum
        prefix: process_agent
      paths:
        - .go/

.linux_builder:
  image: ${LINUX_BUILDER}
  before_script:
    - eval "$(gimme)"
    - export PATH="${GOPATH}/bin:${PATH}"

dependencies:
  extends: [ .linux_builder, .go_process_agent_cache ]
  stage: prebuild
  needs: []
  script:
    - mkdir -p .go
    - go mod download

prebuild_agent:
  extends: [ .linux_builder ]
  cache:
    - key:
        files:
          - go.mod
          - go.sum
        prefix: prebuild_datadog_agent
      paths:
        - prebuild_artifacts/artifacts/*
  stage: prebuild
  image: ${DOCKER_PROXY_URL}/stackstate/datadog_build_system-probe_x64:5151a592
  script:
    - ./prebuild-datadog-agent.sh --generate-no-docker
  artifacts:
    paths:
      - prebuild_artifacts/artifacts/*

test_protobuf_updated:
  extends: [ .linux_builder, .go_process_agent_cache ]
  stage: test
  needs: [ dependencies ]
  script:
    - (cd $(go list -f '{{ .Dir }}' -m github.com/gogo/protobuf); make install)
    - rake protobuf
    - '[[ ! `git status --porcelain` ]] || (echo "ERROR: protobuf should be regenerated and committed" && git diff && false)'

build_linux:
  extends: [ .linux_builder, .go_process_agent_cache ]
  stage: build
  needs: [ dependencies, prebuild_agent ]
  script:
    - export PROCESS_AGENT_VERSION=$(packaging/version.sh)
    - printenv
    - rake build
  artifacts:
    paths:
      - $CI_PROJECT_DIR/process-agent
    expire_in: 2 week
  retry:
    max: 2
    when:
      - always

test:
  extends: [ .linux_builder, .go_process_agent_cache ]
  stage: test
  needs: [ dependencies, prebuild_agent ]
  script:
    - export PROCESS_AGENT_VERSION=$(packaging/version.sh)
    - printenv
    - rake ci
  retry:
    max: 2
    when:
      - always

# Gitlab dedicated runner in a Windows VM
build_windows:
  stage: build
  when: manual
  needs: []
  script:
    - rake deps windres=true --trace
    - .gitlab-scripts/windows_build.cmd
  artifacts:
    expire_in: 2 weeks
    paths:
      - ./process-agent.exe
  tags:
    - windows_agent7_go1.17
  rules:
    - when: manual
      allow_failure: true
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - script_failure

pre_release_windows:
  stage: publish
  needs:
    - build_windows
  script:
    - rake windows-tag-or-commit-artifact
    - aws.exe s3 cp . s3://stackstate-process-agent-2-test/$CI_COMMIT_REF_NAME --recursive --exclude "*" --include "*.exe" --acl public-read
  tags:
    - windows_agent7_go1.17
  rules:
    - when: manual
      allow_failure: true
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - script_failure

publish_binaries:
  stage: publish
  image: ${DOCKER_PROXY_URL}/stackstate/stackstate-process-agent-runner-gitlab:runner_centos7-20221024
  needs:
    - build_linux
  before_script:
    - export PROCESS_AGENT_VERSION=$(eval $VERSION_LOGIC)
  script:
    - echo "PROCESS_AGENT_VERSION=${VERSION}"
    - ls -la $CI_PROJECT_DIR
    - ls -la $CI_PROJECT_DIR/packaging
    - cd $CI_PROJECT_DIR/packaging && ./publish_staging_package.sh

.docker_build:
  image: ${DOCKER_PROXY_URL}/docker:18.06.0
  services:
    - name: ${DOCKER_PROXY_URL}/docker:18.09-dind
      alias: docker
  variables:
    DOCKER_DRIVER: overlay
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u "${docker_user}" -p "${docker_password}" "${DOCKER_REGISTRY}"
    - docker login -u "${quay_user}" -p "${quay_password}" "${QUAY_REGISTRY}"

.publish_linux_docker:
  extends: [ .docker_build ]
  stage: publish
  needs:
    - build_linux
    - prebuild_agent
  script:
    - export BUILD_TAG="${REPO}:${TAG}"
    - ./prebuild-datadog-agent.sh --install-ebpf
    - docker build -t "${BUILD_TAG}" .
    - ./packaging/publish_image.sh $BUILD_TAG $REPO $TAG $EXTRA_TAG

publish_linux_docker:
  extends: [ .publish_linux_docker ]
  variables:
    REPO: $STS_DOCKER_TEST_REPO
    TAG: "$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    EXTRA_TAG: $CI_COMMIT_REF_NAME

publish_k8s_docker:
  extends: [ .publish_linux_docker ]
  variables:
    REPO: $STS_DOCKER_K8S_REPO
    TAG: "$CI_COMMIT_REF_NAME"
    EXTRA_TAG: $CI_COMMIT_SHORT_SHA

publish_linux_docker_release:
  extends: [ .publish_linux_docker ]
  variables:
    REPO: $STS_DOCKER_RELEASE_REPO
    TAG: $CI_COMMIT_REF_NAME
    EXTRA_TAG: latest
  when: manual
  only:
    - tags
    - trigger

build_builder_x64:
  extends: [ .docker_build ]
  stage: build
  rules:
    - when: manual
      allow_failure: true
  script:
    - cd .cd-builders/builder-x64; pwd
    - export RUNTIMETAG="$(date +%Y%m%d)-${CI_COMMIT_SHA:0:7}"; echo ${RUNTIMETAG}
    - docker build -t stackstate/stackstate-process-agent-runner-gitlab:llvmclang11-x64-${RUNTIMETAG} .
    - docker push stackstate/stackstate-process-agent-runner-gitlab:llvmclang11-x64-${RUNTIMETAG}
  timeout: 3 hours
  tags:
    - sts-k8s-xl-runner

build_runner_centos7:
  extends: [ .docker_build ]
  stage: build
  retry:
    max: 2
    when:
      - always
  rules:
    - when: manual
      allow_failure: true
  script:
    - cd $RUNNER7_DIR
    - pwd
    - export RUNTIMETAG=$(date +%Y%m%d)
    - docker build -t stackstate/stackstate-process-agent-runner-gitlab:runner_centos7-${RUNTIMETAG} .
    - docker push stackstate/stackstate-process-agent-runner-gitlab:runner_centos7-${RUNTIMETAG}
