stages:
  - triggers
  - postbuild

agent_x86_64:
  stage: triggers
  variables:
    ARCH: x86_64
    DD_ARCH: amd64
    DOCKER_ARCH: amd64
  trigger:
    include: .gitlab-ci-x64.yml
    strategy: depend
  rules:
    - when: always


agent_arm64:
  stage: triggers
  variables:
    ARCH: aarch64
    DD_ARCH: arm64
    DOCKER_ARCH: arm64
  trigger:
    include: .gitlab-ci-arm.yml
    strategy: depend
  rules:
    - when: always

merge_docker_manifest:
  stage: postbuild
  needs: [ agent_x86_64, agent_arm64 ]
  trigger:
    include: .gitlab-ci-docker.yml
    strategy: depend
  rules:
    - when: always