#!/bin/sh

INSTALL_DIR=/opt/sts-process-agent
LOG_DIR=/var/log/sts-process-agent.log

# added sts-agent group if not exists
getent group sts-agent >/dev/null || (echo "Creating sts-agent group" && addgroup --system sts-agent --quiet)
# check if sts-agent user exists
id -u sts-agent >/dev/null 2>&1
USER_EXISTS=$?
if [ ! $USER_EXISTS -eq 0 ]; then
    echo "Creating sts-agent user"
    adduser --system sts-agent --disabled-login --shell /bin/bash --home ${INSTALL_DIR} --no-create-home --group --quiet
elif id -nG sts-agent | grep --invert-match --word-regexp --quiet 'sts-agent'; then
    # User exists but is not part of the sts-agent group
    echo "Adding sts-agent user to sts-agent group"
    usermod -g sts-agent sts-agent
fi

# set proper rights to dd-agent user
chown -R sts-agent:sts-agent ${INSTALL_DIR}
if [ -f $LOG_DIR ]; then
    chown -R sts-agent:sts-agent ${LOG_DIR}
else
    touch ${LOG_DIR}
    chown -R sts-agent:sts-agent ${LOG_DIR}
fi

echo "Adding sts-process-agent to start on boot..."
update-rc.d -f sts-process-agent defaults
