// Code generated by goderive DO NOT EDIT.

package config

import (
	"regexp"
)

// deriveFmapConstructRegex returns a list where each element of the input list has been morphed by the input function.
func deriveFmapConstructRegex(f func(string) *regexp.Regexp, list []string) []*regexp.Regexp {
	out := make([]*regexp.Regexp, len(list))
	for i, elem := range list {
		out[i] = f(elem)
	}
	return out
}
