#!/bin/sh -x

INSTALL_DIR=/opt/sts-process-agent
LOG_DIR=/var/log/sts-process-agent.log

getent group sts-agent >/dev/null || groupadd -r sts-agent
getent passwd sts-agent >/dev/null || \
useradd -r -M -g sts-agent -d $INSTALL_DIR -s /bin/bash -c "Datadog Agent" sts-agent

# set proper rights to sts-agent user
chown -R sts-agent:sts-agent ${INSTALL_DIR}
if [ -f $LOG_DIR ]; then
    chown -R sts-agent:sts-agent ${LOG_DIR}
else
    touch ${LOG_DIR}
    chown -R sts-agent:sts-agent ${LOG_DIR}
fi

echo "Adding dd-process-agent to start on boot..."
chkconfig --add sts-process-agent
