#!/bin/bash

# https://regex-golang.appspot.com/assets/html/index.html

export REPLACE_SCOPE="../config ../agent ../checks"
export REPLACE_MODE=-w # "-d"

gofmt -l $REPLACE_MODE -r '"DD_HOSTNAME" -> "STS_HOSTNAME"'  $REPLACE_SCOPE
echo gofmt -l $REPLACE_MODE -r '"DD_API_KEY" -> "STS_API_KEY"' $REPLACE_SCOPE
gofmt -l $REPLACE_MODE -r '"DD_API_KEY" -> "STS_API_KEY"' $REPLACE_SCOPE
gofmt -l $REPLACE_MODE -r '"DD_CUSTOM_SENSITIVE_WORDS" -> "STS_CUSTOM_SENSITIVE_WORDS"' $REPLACE_SCOPE
gofmt -l $REPLACE_MODE -r '"DD_SCRUB_ARGS" -> "STS_SCRUB_ARGS"' $REPLACE_SCOPE
gofmt -l $REPLACE_MODE -r '"DD_CUSTOM_SENSITIVE_WORDS" -> "STS_CUSTOM_SENSITIVE_WORDS"' $REPLACE_SCOPE
gofmt -l $REPLACE_MODE -r '"DD_LOG_LEVEL" -> "STS_LOG_LEVEL"' $REPLACE_SCOPE
gofmt -l $REPLACE_MODE -r '"DD_LOGS_STDOUT" -> "STS_LOGS_STDOUT"' $REPLACE_SCOPE
gofmt -l $REPLACE_MODE -r '"DD_LOG_TO_CONSOLE" -> "STS_LOG_TO_CONSOLE"' $REPLACE_SCOPE
gofmt -l $REPLACE_MODE -r '"DD_PROCESS_AGENT_ENABLED" -> "STS_PROCESS_AGENT_ENABLED"' $REPLACE_SCOPE
gofmt -l $REPLACE_MODE -r '"DD_PROCESS_AGENT_URL" -> "STS_PROCESS_AGENT_URL"' $REPLACE_SCOPE
gofmt -l $REPLACE_MODE -r '"DD_STRIP_PROCESS_ARGS" -> "STS_STRIP_PROCESS_ARGS"' $REPLACE_SCOPE
gofmt -l $REPLACE_MODE -r '"DD_AGENT_PY" -> "STS_AGENT_PY"' $REPLACE_SCOPE
gofmt -l $REPLACE_MODE -r '"DD_AGENT_PY_ENV" -> "STS_AGENT_PY_ENV"' $REPLACE_SCOPE
gofmt -l $REPLACE_MODE -r '"DD_DOGSTATSD_PORT" -> "STS_DOGSTATSD_PORT"' $REPLACE_SCOPE
gofmt -l $REPLACE_MODE -r '"DD_BIND_HOST" -> "STS_BIND_HOST"' $REPLACE_SCOPE
gofmt -l $REPLACE_MODE -r '"DD_COLLECT_DOCKER_NETWORK" -> "STS_COLLECT_DOCKER_NETWORK"' $REPLACE_SCOPE
gofmt -l $REPLACE_MODE -r '"DD_CONTAINER_BLACKLIST" -> "STS_CONTAINER_BLACKLIST"' $REPLACE_SCOPE
gofmt -l $REPLACE_MODE -r '"DD_CONTAINER_WHITELIST" -> "STS_CONTAINER_WHITELIST"' $REPLACE_SCOPE
gofmt -l $REPLACE_MODE -r '"DD_CONTAINER_CACHE_DURATION" -> "STS_CONTAINER_CACHE_DURATION"' $REPLACE_SCOPE
gofmt -l $REPLACE_MODE -r '"DD_PROCESS_AGENT_CONTAINER_SOURCE" -> "STS_PROCESS_AGENT_CONTAINER_SOURCE"' $REPLACE_SCOPE
gofmt -l $REPLACE_MODE -r '"DD_NETWORK_TRACING_ENABLED" -> "STS_NETWORK_TRACING_ENABLED"' $REPLACE_SCOPE
gofmt -l $REPLACE_MODE -r '"DD_NETWORK_TRACING_ENABLED" -> "STS_NETWORK_TRACING_ENABLED"' $REPLACE_SCOPE
gofmt -l $REPLACE_MODE -r '"DD_NETTRACER_SOCKET" -> "STS_NETTRACER_SOCKET"' $REPLACE_SCOPE

echo "Checking replacements..."

which rgrep
rgrep --include=*.go "\"DD_"  $PWD/../agent $PWD/../config $PWD/../checks

RESULT=$?
if [ $RESULT -eq 0 ]; then
  echo "Check result for found DD_, adjust branding logic"
  exit 1
else
  echo "Looks ok, return code $RESULT"
fi

