apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-server
  labels:
    app.kubernetes.io/name: postgres-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres-server
    spec:
      containers:
      - name: postgres
        image: postgres:14-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "mysecretpassword"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app.kubernetes.io/name: postgres-server
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres-client
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres-client
    spec:
      containers:
      - name: client
        image: postgres:14-alpine
        env:
        - name: PGPASSWORD
          value: "mysecretpassword"
        command: ["sh", "-c"]
        args:          
          #
          #
          # For 90000 seconds we send a select query every 1 second on the same PostgreSQL connection.
          # Then we start again with a new connection.
          #
          #
          - |
            echo "Waiting for PostgreSQL to be ready..."
            until pg_isready -h postgres-service -U postgres; do
              sleep 1;
            done;
            echo "PostgreSQL is ready."
            echo "Creating table 'demo' if not exists..."
            psql -h postgres-service -U postgres -c "CREATE TABLE IF NOT EXISTS demo (id SERIAL PRIMARY KEY, name VARCHAR(50));"
            echo "Inserting initial entry into 'demo' table..."
            psql -h postgres-service -U postgres -c "INSERT INTO demo (name) VALUES ('initial entry');"
            echo "Starting periodic SELECT queries on 'demo' table..."
            while true; do
              pgbench -h postgres-service -U postgres -d postgres -c 1 -T 90000 -n -f <(echo "SELECT * FROM demo; \sleep 1")
            done;
